In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("Datasets/Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
X = dataset.iloc[:,[3,4,5,6,7,8,9,10,11,12]].values
X 

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y = dataset.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_enc_X_country = LabelEncoder()
X[:,1] = label_enc_X_country.fit_transform(X[:,1])
X[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [7]:
label_enc_X_gender = LabelEncoder()
X[:,2] =  label_enc_X_gender.fit_transform(X[:,2])
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [8]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
one_hot_enc = OneHotEncoder(categorical_features=[1])
X = one_hot_enc.fit_transform(X).toarray()
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [10]:
X = X[:,1:]
X

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.02000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   7.09000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  1.00000000e+00,   0.00000000e+00,   7.72000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   7.92000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [13]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ..., 
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [14]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [58]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [59]:
classifier1 = Sequential()

In [60]:
classifier1.add(Dense(units=6,activation='relu',input_dim=11,bias_initializer='uniform'))


In [61]:
classifier1.add(Dense(units=6,activation='relu',bias_initializer='uniform'))

In [62]:
classifier1.add(Dense(units=1,activation='sigmoid',input_dim=11,bias_initializer='uniform'))

In [63]:
classifier1.compile(optimizer='adam',loss='binary_crossentropy',
              metrics=['accuracy'])

In [64]:
classifier1.fit(X_train,y_train,epochs=100, batch_size=10)

Epoch 1/100
8000/8000 [==============================] - 1s - loss: 0.4778 - acc: 0.7894     
Epoch 2/100
8000/8000 [==============================] - 0s - loss: 0.4093 - acc: 0.8236     
Epoch 3/100
8000/8000 [==============================] - 0s - loss: 0.3854 - acc: 0.8396     
Epoch 4/100
8000/8000 [==============================] - 0s - loss: 0.3703 - acc: 0.8480     
Epoch 5/100
8000/8000 [==============================] - 0s - loss: 0.3606 - acc: 0.8501     
Epoch 6/100
8000/8000 [==============================] - 0s - loss: 0.3542 - acc: 0.8534     - ETA: 0s - loss: 0.3444 - acc: 0
Epoch 7/100
8000/8000 [==============================] - 0s - loss: 0.3511 - acc: 0.8590     
Epoch 8/100
8000/8000 [==============================] - 0s - loss: 0.3494 - acc: 0.8594     
Epoch 9/100
8000/8000 [==============================] - 0s - loss: 0.3478 - acc: 0.8585     
Epoch 10/100
8000/8000 [==============================] - 0s - loss: 0.3462 - acc: 0.8607     
Epoch 11/100
8000/8000 [==

8000/8000 [==============================] - 0s - loss: 0.3330 - acc: 0.8630     
Epoch 87/100
8000/8000 [==============================] - 0s - loss: 0.3327 - acc: 0.8622     
Epoch 88/100
8000/8000 [==============================] - 0s - loss: 0.3333 - acc: 0.8621     
Epoch 89/100
8000/8000 [==============================] - 0s - loss: 0.3330 - acc: 0.8624     
Epoch 90/100
8000/8000 [==============================] - 0s - loss: 0.3328 - acc: 0.8597     
Epoch 91/100
8000/8000 [==============================] - 0s - loss: 0.3333 - acc: 0.8619     
Epoch 92/100
8000/8000 [==============================] - 0s - loss: 0.3327 - acc: 0.8601     
Epoch 93/100
8000/8000 [==============================] - 1s - loss: 0.3330 - acc: 0.8616     
Epoch 94/100
8000/8000 [==============================] - 1s - loss: 0.3331 - acc: 0.8624     
Epoch 95/100
8000/8000 [==============================] - 1s - loss: 0.3325 - acc: 0.8634     
Epoch 96/100
8000/8000 [==============================] - 1s - 

In [65]:
preds = classifier1.predict(X_test)
preds

array([[ 0.31334487],
       [ 0.27568659],
       [ 0.16906163],
       ..., 
       [ 0.13805617],
       [ 0.15984245],
       [ 0.19076078]], dtype=float32)

In [66]:
preds = (preds>0.5)
preds

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [67]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,preds)
cm

array([[1510,   85],
       [ 194,  211]])

In [68]:
accuracy_score(y_test,preds)

0.86050000000000004

In [69]:
(classifier1.predict(scaler.transform(np.array([[0.0,0.0,600,1,40,3,60000,2,1,1,50000]])))>0.5)

array([[False]], dtype=bool)

In [15]:
from keras.wrappers.scikit_learn import KerasClassifier

In [16]:
from sklearn.model_selection import cross_val_score

In [ ]:
def buildclassifier():
    classifier1 = Sequential()
    classifier1.add(Dense(units=6,activation='relu',input_dim=11,bias_initializer='uniform'))
    classifier1.add(Dense(units=6,activation='relu',bias_initializer='uniform'))
    classifier1.add(Dense(units=1,activation='sigmoid',input_dim=11,bias_initializer='uniform'))
    classifier1.compile(optimizer='adam',loss='binary_crossentropy',
                  metrics=['accuracy'])